---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: localization-ui
  name: localization-ui
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: localization-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: localization-ui
    spec:
      containers:
      - image: docker.io/maruf571/localization-ui:1.0.10
        imagePullPolicy: Always
        name: localization-ui
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: localization-ui
  name: localization-ui-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: localization-ui
  sessionAffinity: None
  type: LoadBalancer
